run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/ops-tool
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic

linters:
  disable-all: true
  enable:
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - typecheck
    - unconvert
    - whitespace
    - revive
