name: Build

# Triggers the workflow on push or pull request events but only for the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b" #v3.0.2
      - name: "Lint"
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b" #v3.0.2
      - name: "Test"
        run: make test
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b" #v3.0.2
      - name: "Build"
        run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 #v3.1.0
        with:
          name: dist
          path: |
            dist/*
